#!/bin/bash

GREEN=$(tput setaf 10)
YELLOW=$(tput setaf 11)
NONE=$(tput sgr0)

echo "[${GREEN}${PWD}${NONE}] Running '${YELLOW}./bootstrap${NONE}' in external dependencies"
(cd external/sdl2xx && ./bootstrap) || exit 1

echo "[${GREEN}${PWD}${NONE}] Running '${YELLOW}autoreconf --install $@${NONE}'"
exec autoreconf --install "$@"
